apiVersion: v1
kind: Config
clusters:
- name: example-cluster
  cluster:
    server: https://1.2.3.4:6443
    certificate-authority: /path/to/ca.crt
    insecure-skip-tls-verify: false
users:
- name: example-user
  user:
    client-certificate: /path/to/client.crt
    client-key: /path/to/client.key
    token: your-bearer-token
contexts:
- name: example-context
  context:
    cluster: example-cluster
    user: example-user
    namespace: default
current-context: example-context
preferences: {}
