apiVersion: v1
kind: LimitRange
metadata:
  name: example-limit-range
  namespace: mynamespace
spec:
  limits:
    - max:
        cpu: "2"
        memory: "1Gi"
      min:
        cpu: "200m"
        memory: "6Mi"
      default:
        cpu: "500m"
        memory: "128Mi"
      defaultRequest:
        cpu: "300m"
        memory: "64Mi"
      type: Container
    - max:
        storage: "10Gi"
      min:
        storage: "1Gi"
      default:
        storage: "5Gi"
      defaultRequest:
        storage: "3Gi"
      type: PersistentVolumeClaim
    - max:
        pods: "10"
      min:
        pods: "1"
      type: Pod
