apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
  labels:
    app: myapp
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
stringData:
  api-key: "my-api-key"
  token: "my-token"
immutable: true
